apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    metadata:
      annotations:
        # Keep at least 1 pod running to prevent scale to zero
        autoscaling.knative.dev/minScale: "1"
    spec:
      serviceAccountName: hello-sa
      containers:
        - image: docker.io/biongo/hello:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m" # Minimum guaranteed CPU
              memory: "128Mi" # Minimum guaranteed Memory
            limits:
              cpu: "500m" # Maximum allowed CPU
              memory: "256Mi" # Maximum allowed Memory
          securityContext:
            allowPrivilegeEscalation: false # Do not allow privilege escalation
            runAsNonRoot: true # Force container to run as non-root user
            capabilities:
              drop:
                - ALL # Drop all Linux capabilities
            seccompProfile:
              type: RuntimeDefault # Use the runtime's default seccomp profile
