apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-sa # 👈 指定使用自定义 SA
      containers:
        - name: my-container
          image: docker.io/biongo/demo:latest
